-- =====================================================
-- 09-sample-queries.sql
-- Example clinical queries demonstrating dual-warehouse architecture
-- Performance-optimized queries for patient dashboards and analytics
-- =====================================================

USE ROLE CLINICAL_ANALYST;
USE DATABASE CLINICAL_DB;
USE WAREHOUSE CLINICAL_INTERACTIVE_WH;  -- Fast queries for dashboards

-- =====================================================
-- PATIENT DASHBOARD QUERIES (<100ms target)
-- =====================================================

-- Query 1: Patient Summary Dashboard
-- Target: <50ms with Interactive Tables
SELECT
    p.PATIENT_ID,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
    p.DATE_OF_BIRTH,
    DATEDIFF('YEAR', p.DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    p.GENDER,
    COUNT(DISTINCT e.ENCOUNTER_ID) AS TOTAL_ENCOUNTERS,
    COUNT(DISTINCT l.LAB_RESULT_ID) AS TOTAL_LAB_TESTS,
    MAX(e.ENCOUNTER_DATE) AS LAST_VISIT_DATE,
    DATEDIFF('DAY', MAX(e.ENCOUNTER_DATE), CURRENT_DATE()) AS DAYS_SINCE_LAST_VISIT
FROM CLINICAL_DB.CURATED.PATIENTS p
LEFT JOIN CLINICAL_DB.CURATED.ENCOUNTERS e ON p.PATIENT_ID = e.PATIENT_ID
LEFT JOIN CLINICAL_DB.CURATED.LAB_RESULTS l ON p.PATIENT_ID = l.PATIENT_ID
WHERE p.PATIENT_ID = 'PAT-12345'  -- Parameter from application
GROUP BY 1, 2, 3, 4, 5;

-- Query 2: Recent Encounters for Patient
-- Target: <30ms
SELECT
    e.ENCOUNTER_ID,
    e.ENCOUNTER_TYPE,
    e.ENCOUNTER_DATE,
    e.CHIEF_COMPLAINT,
    e.DIAGNOSIS_CODE,
    e.DIAGNOSIS_DESCRIPTION,
    e.STATUS
FROM CLINICAL_DB.CURATED.ENCOUNTERS e
WHERE e.PATIENT_ID = 'PAT-12345'
ORDER BY e.ENCOUNTER_DATE DESC
LIMIT 10;

-- Query 3: Recent Lab Results with Abnormal Flags
-- Target: <40ms
SELECT
    l.TEST_DATE,
    l.TEST_NAME,
    l.RESULT_VALUE,
    l.RESULT_UNIT,
    l.REFERENCE_RANGE,
    l.ABNORMAL_FLAG,
    CASE
        WHEN l.ABNORMAL_FLAG = 'HIGH' THEN '⬆️ Above Normal'
        WHEN l.ABNORMAL_FLAG = 'LOW' THEN '⬇️ Below Normal'
        WHEN l.ABNORMAL_FLAG = 'CRITICAL' THEN '🚨 Critical'
        ELSE '✅ Normal'
    END AS RESULT_STATUS
FROM CLINICAL_DB.CURATED.LAB_RESULTS l
WHERE l.PATIENT_ID = 'PAT-12345'
ORDER BY l.TEST_DATE DESC
LIMIT 20;

-- =====================================================
-- CLINICAL ANALYTICS QUERIES
-- =====================================================

-- Query 4: Diabetes Patient Cohort Analysis
-- Find all patients with diabetes diagnosis and HbA1c trends
SELECT
    p.PATIENT_ID,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
    DATEDIFF('YEAR', p.DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    p.GENDER,
    COUNT(DISTINCT e.ENCOUNTER_ID) AS ENCOUNTER_COUNT,
    AVG(
        CASE 
            WHEN l.TEST_CODE = 'HBA1C' 
            THEN TRY_CAST(l.RESULT_VALUE AS FLOAT)
        END
    ) AS AVG_HBA1C,
    MAX(e.ENCOUNTER_DATE) AS LAST_VISIT
FROM CLINICAL_DB.CURATED.PATIENTS p
INNER JOIN CLINICAL_DB.CURATED.ENCOUNTERS e 
    ON p.PATIENT_ID = e.PATIENT_ID
LEFT JOIN CLINICAL_DB.CURATED.LAB_RESULTS l 
    ON e.ENCOUNTER_ID = l.ENCOUNTER_ID
WHERE e.DIAGNOSIS_CODE LIKE 'E11%'  -- ICD-10 Type 2 Diabetes
    AND e.ENCOUNTER_DATE >= DATEADD('YEAR', -2, CURRENT_DATE())
GROUP BY 1, 2, 3, 4
HAVING AVG_HBA1C > 7.0  -- Uncontrolled diabetes threshold
ORDER BY AVG_HBA1C DESC
LIMIT 100;

-- Query 5: High-Risk Patient Alert Dashboard
-- Patients with critical lab values in last 24 hours
SELECT
    p.PATIENT_ID,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
    p.PHONE,
    l.TEST_NAME,
    l.RESULT_VALUE,
    l.RESULT_UNIT,
    l.REFERENCE_RANGE,
    l.TEST_DATE,
    DATEDIFF('HOUR', l.TEST_DATE, CURRENT_TIMESTAMP()) AS HOURS_AGO,
    '🚨 CRITICAL' AS ALERT_LEVEL
FROM CLINICAL_DB.CURATED.LAB_RESULTS l
INNER JOIN CLINICAL_DB.CURATED.PATIENTS p ON l.PATIENT_ID = p.PATIENT_ID
WHERE l.ABNORMAL_FLAG = 'CRITICAL'
    AND l.TEST_DATE >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
ORDER BY l.TEST_DATE DESC;

-- Query 6: Emergency Department Volume Tracking
-- Real-time ED census by hour
SELECT
    DATE_TRUNC('HOUR', e.ENCOUNTER_DATE) AS HOUR,
    COUNT(*) AS ED_VISITS,
    COUNT(DISTINCT e.PATIENT_ID) AS UNIQUE_PATIENTS,
    AVG(
        CASE 
            WHEN e.DISCHARGE_DATE IS NOT NULL 
            THEN DATEDIFF('MINUTE', e.ENCOUNTER_DATE, e.DISCHARGE_DATE)
        END
    ) AS AVG_LENGTH_OF_STAY_MINUTES
FROM CLINICAL_DB.CURATED.ENCOUNTERS e
WHERE e.ENCOUNTER_TYPE = 'EMERGENCY'
    AND e.ENCOUNTER_DATE >= DATEADD('DAY', -1, CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY 1 DESC;

-- Query 7: Provider Performance Dashboard
-- Top providers by patient volume and outcomes
SELECT
    e.PROVIDER_ID,
    COUNT(DISTINCT e.PATIENT_ID) AS UNIQUE_PATIENTS_SEEN,
    COUNT(DISTINCT e.ENCOUNTER_ID) AS TOTAL_ENCOUNTERS,
    AVG(DATEDIFF('MINUTE', e.ENCOUNTER_DATE, e.DISCHARGE_DATE)) AS AVG_ENCOUNTER_DURATION_MIN,
    COUNT(DISTINCT CASE WHEN e.STATUS = 'ADMITTED' THEN e.ENCOUNTER_ID END) AS ADMISSIONS,
    (COUNT(DISTINCT CASE WHEN e.STATUS = 'ADMITTED' THEN e.ENCOUNTER_ID END) * 100.0 / 
     COUNT(DISTINCT e.ENCOUNTER_ID)) AS ADMISSION_RATE_PCT
FROM CLINICAL_DB.CURATED.ENCOUNTERS e
WHERE e.ENCOUNTER_DATE >= DATEADD('MONTH', -3, CURRENT_DATE())
    AND e.PROVIDER_ID IS NOT NULL
GROUP BY 1
ORDER BY 2 DESC
LIMIT 50;

-- =====================================================
-- POPULATION HEALTH QUERIES
-- =====================================================

-- Query 8: Chronic Disease Prevalence by Demographics
SELECT
    CASE
        WHEN DATEDIFF('YEAR', p.DATE_OF_BIRTH, CURRENT_DATE()) < 18 THEN '0-17'
        WHEN DATEDIFF('YEAR', p.DATE_OF_BIRTH, CURRENT_DATE()) < 45 THEN '18-44'
        WHEN DATEDIFF('YEAR', p.DATE_OF_BIRTH, CURRENT_DATE()) < 65 THEN '45-64'
        ELSE '65+'
    END AS AGE_GROUP,
    p.GENDER,
    COUNT(DISTINCT p.PATIENT_ID) AS TOTAL_PATIENTS,
    COUNT(DISTINCT CASE WHEN e.DIAGNOSIS_CODE LIKE 'E11%' THEN p.PATIENT_ID END) AS DIABETES_COUNT,
    COUNT(DISTINCT CASE WHEN e.DIAGNOSIS_CODE LIKE 'I10%' THEN p.PATIENT_ID END) AS HYPERTENSION_COUNT,
    COUNT(DISTINCT CASE WHEN e.DIAGNOSIS_CODE LIKE 'J44%' THEN p.PATIENT_ID END) AS COPD_COUNT,
    (COUNT(DISTINCT CASE WHEN e.DIAGNOSIS_CODE LIKE 'E11%' THEN p.PATIENT_ID END) * 100.0 / 
     COUNT(DISTINCT p.PATIENT_ID)) AS DIABETES_PREVALENCE_PCT
FROM CLINICAL_DB.CURATED.PATIENTS p
LEFT JOIN CLINICAL_DB.CURATED.ENCOUNTERS e ON p.PATIENT_ID = e.PATIENT_ID
WHERE p.DELETED_AT IS NULL
GROUP BY 1, 2
ORDER BY 1, 2;

-- Query 9: Readmission Risk Analysis (30-day readmissions)
WITH admissions AS (
    SELECT
        e1.PATIENT_ID,
        e1.ENCOUNTER_ID AS INITIAL_ENCOUNTER_ID,
        e1.DISCHARGE_DATE AS INITIAL_DISCHARGE,
        e2.ENCOUNTER_ID AS READMIT_ENCOUNTER_ID,
        e2.ENCOUNTER_DATE AS READMIT_DATE,
        DATEDIFF('DAY', e1.DISCHARGE_DATE, e2.ENCOUNTER_DATE) AS DAYS_TO_READMIT
    FROM CLINICAL_DB.CURATED.ENCOUNTERS e1
    INNER JOIN CLINICAL_DB.CURATED.ENCOUNTERS e2
        ON e1.PATIENT_ID = e2.PATIENT_ID
        AND e2.ENCOUNTER_DATE > e1.DISCHARGE_DATE
        AND DATEDIFF('DAY', e1.DISCHARGE_DATE, e2.ENCOUNTER_DATE) <= 30
    WHERE e1.STATUS = 'DISCHARGED'
        AND e1.ENCOUNTER_TYPE IN ('INPATIENT', 'EMERGENCY')
        AND e1.DISCHARGE_DATE >= DATEADD('MONTH', -6, CURRENT_DATE())
)
SELECT
    a.PATIENT_ID,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PATIENT_NAME,
    DATEDIFF('YEAR', p.DATE_OF_BIRTH, CURRENT_DATE()) AS AGE,
    a.INITIAL_DISCHARGE,
    a.READMIT_DATE,
    a.DAYS_TO_READMIT,
    e.DIAGNOSIS_CODE AS INITIAL_DIAGNOSIS,
    e2.DIAGNOSIS_CODE AS READMIT_DIAGNOSIS
FROM admissions a
INNER JOIN CLINICAL_DB.CURATED.PATIENTS p ON a.PATIENT_ID = p.PATIENT_ID
INNER JOIN CLINICAL_DB.CURATED.ENCOUNTERS e ON a.INITIAL_ENCOUNTER_ID = e.ENCOUNTER_ID
INNER JOIN CLINICAL_DB.CURATED.ENCOUNTERS e2 ON a.READMIT_ENCOUNTER_ID = e2.ENCOUNTER_ID
ORDER BY a.DAYS_TO_READMIT;

-- Query 10: Lab Test Turnaround Time Analysis
SELECT
    l.TEST_NAME,
    COUNT(*) AS TEST_COUNT,
    AVG(DATEDIFF('HOUR', l.TEST_DATE, l.RESULT_DATE)) AS AVG_TURNAROUND_HOURS,
    MEDIAN(DATEDIFF('HOUR', l.TEST_DATE, l.RESULT_DATE)) AS MEDIAN_TURNAROUND_HOURS,
    PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY DATEDIFF('HOUR', l.TEST_DATE, l.RESULT_DATE)) AS P95_TURNAROUND_HOURS,
    COUNT(CASE WHEN DATEDIFF('HOUR', l.TEST_DATE, l.RESULT_DATE) > 24 THEN 1 END) AS DELAYED_COUNT,
    (COUNT(CASE WHEN DATEDIFF('HOUR', l.TEST_DATE, l.RESULT_DATE) > 24 THEN 1 END) * 100.0 / COUNT(*)) AS DELAYED_PCT
FROM CLINICAL_DB.CURATED.LAB_RESULTS l
WHERE l.TEST_DATE >= DATEADD('MONTH', -3, CURRENT_DATE())
    AND l.RESULT_DATE IS NOT NULL
GROUP BY 1
HAVING COUNT(*) >= 100
ORDER BY 3 DESC
LIMIT 20;

-- =====================================================
-- RESEARCH & DE-IDENTIFIED QUERIES
-- =====================================================

-- Query 11: De-identified Research Cohort for Clinical Trial
-- Uses AI_REDACT views for HIPAA Safe Harbor compliance
SELECT
    r.PATIENT_HASH_ID,
    r.AGE_GROUP,
    r.GENDER,
    r.STATE,
    r.TOTAL_ENCOUNTERS,
    r.TOTAL_LAB_TESTS,
    r.FIRST_ENCOUNTER_DAY,
    r.LAST_ENCOUNTER_DAY
FROM CLINICAL_DB.RESEARCH_DEIDENTIFIED.V_RESEARCH_COHORT r
WHERE r.AGE_GROUP IN ('45-64', '65+')
    AND r.TOTAL_ENCOUNTERS >= 5
    AND r.STATE IN ('NY', 'NJ', 'CT')
ORDER BY r.TOTAL_LAB_TESTS DESC
LIMIT 500;

-- =====================================================
-- COST OPTIMIZATION QUERIES
-- =====================================================

-- Query 12: Check Query Performance & Cost
-- Analyze this query's own execution
SELECT
    QUERY_ID,
    QUERY_TEXT,
    WAREHOUSE_NAME,
    TOTAL_ELAPSED_TIME / 1000 AS EXECUTION_SECONDS,
    BYTES_SCANNED / POWER(1024, 3) AS GB_SCANNED,
    ROWS_PRODUCED,
    CREDITS_USED_CLOUD_SERVICES,
    CASE WAREHOUSE_SIZE
        WHEN 'XSMALL' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 1 * 2
        WHEN 'SMALL' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 2 * 2
        ELSE 0
    END AS ESTIMATED_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_ID = LAST_QUERY_ID()
ORDER BY START_TIME DESC
LIMIT 1;

-- =====================================================
-- OPERATIONAL MONITORING QUERIES
-- =====================================================

-- Query 13: Dynamic Table Refresh Status
-- Monitor dual-warehouse Dynamic Tables
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    REFRESH_MODE,
    WAREHOUSE,
    TARGET_LAG,
    DATA_TIMESTAMP,
    LAST_REFRESH_TIME,
    DATEDIFF('MINUTE', LAST_REFRESH_TIME, CURRENT_TIMESTAMP()) AS MINUTES_SINCE_REFRESH,
    CASE
        WHEN DATEDIFF('MINUTE', LAST_REFRESH_TIME, CURRENT_TIMESTAMP()) > 30 
            THEN '
